// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_pizza.Models;

#nullable disable

namespace dotnet_pizza.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250506132412_AddKategoriTable")]
    partial class AddKategoriTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("dotnet_pizza.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAdi = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAdi = "Citir"
                        },
                        new
                        {
                            Id = 3,
                            KategoriAdi = "Burger"
                        },
                        new
                        {
                            Id = 4,
                            KategoriAdi = "Icecek"
                        },
                        new
                        {
                            Id = 5,
                            KategoriAdi = "Borek"
                        },
                        new
                        {
                            Id = 6,
                            KategoriAdi = "Atistirmalik"
                        },
                        new
                        {
                            Id = 7,
                            KategoriAdi = "Tost"
                        });
                });

            modelBuilder.Entity("dotnet_pizza.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price1")
                        .HasColumnType("REAL");

                    b.Property<int?>("Price2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tanitim")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "pizza.jpg",
                            KategoriId = 1,
                            Price1 = 260.0,
                            Price2 = 320,
                            ProductName = "Pizza2",
                            Tanitim = "sucuklu,kaşarli"
                        },
                        new
                        {
                            Id = 2,
                            Image = "pizza.jpg",
                            KategoriId = 1,
                            Price1 = 260.0,
                            Price2 = 320,
                            ProductName = "Pizza2",
                            Tanitim = "sucuklu,kaşarli"
                        },
                        new
                        {
                            Id = 3,
                            Image = "pizza.jpg",
                            KategoriId = 1,
                            Price1 = 260.0,
                            Price2 = 320,
                            ProductName = "Pizza4",
                            Tanitim = "sucuklu,kaşarli"
                        },
                        new
                        {
                            Id = 4,
                            Image = "pizza.jpg",
                            KategoriId = 1,
                            Price1 = 260.0,
                            Price2 = 320,
                            ProductName = "Pizza5",
                            Tanitim = "sucuklu,kaşarli"
                        },
                        new
                        {
                            Id = 5,
                            Image = "pizza.jpg",
                            KategoriId = 1,
                            Price1 = 260.0,
                            Price2 = 320,
                            ProductName = "Pizza6",
                            Tanitim = "sucuklu,kaşarli"
                        },
                        new
                        {
                            Id = 6,
                            Image = "burger.jpg",
                            KategoriId = 3,
                            Price1 = 260.0,
                            ProductName = "Burger1",
                            Tanitim = "tavuk Burger"
                        },
                        new
                        {
                            Id = 7,
                            Image = "burger.jpg",
                            KategoriId = 3,
                            Price1 = 250.0,
                            ProductName = "Burger2",
                            Tanitim = "tavuk Burger"
                        },
                        new
                        {
                            Id = 8,
                            Image = "burger.jpg",
                            KategoriId = 3,
                            Price1 = 240.0,
                            ProductName = "Burger3",
                            Tanitim = "tavuk Burger"
                        },
                        new
                        {
                            Id = 9,
                            Image = "burger2.jpg",
                            KategoriId = 2,
                            Price1 = 230.0,
                            ProductName = "Çıtır1",
                            Tanitim = "tavuk Burger"
                        },
                        new
                        {
                            Id = 20,
                            Image = "burger2.jpg",
                            KategoriId = 2,
                            Price1 = 230.0,
                            ProductName = "Çıtır2",
                            Tanitim = "tavuk Burger"
                        },
                        new
                        {
                            Id = 10,
                            KategoriId = 5,
                            Price1 = 260.0,
                            ProductName = "Börek1",
                            Tanitim = "tavuk Burger"
                        },
                        new
                        {
                            Id = 11,
                            KategoriId = 7,
                            Price1 = 260.0,
                            ProductName = "Tost2",
                            Tanitim = "tavuk Burger"
                        },
                        new
                        {
                            Id = 12,
                            KategoriId = 4,
                            Price1 = 260.0,
                            ProductName = "İçecek1"
                        },
                        new
                        {
                            Id = 13,
                            KategoriId = 6,
                            Price1 = 260.0,
                            ProductName = "Atistirmalik1"
                        });
                });

            modelBuilder.Entity("dotnet_pizza.Models.Product", b =>
                {
                    b.HasOne("dotnet_pizza.Models.Kategori", "Kategori")
                        .WithMany("Products")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("dotnet_pizza.Models.Kategori", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
