// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_pizza.Models;

#nullable disable

namespace dotnet_pizza.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250504120531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("dotnet_pizza.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tanitim")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 260.0,
                            ProductName = "Pizza2",
                            Tanitim = "sucuklu,kaşarli"
                        },
                        new
                        {
                            Id = 2,
                            Price = 260.0,
                            ProductName = "Pizza2",
                            Tanitim = "sucuklu,kaşarli"
                        },
                        new
                        {
                            Id = 3,
                            Price = 260.0,
                            ProductName = "Pizza4",
                            Tanitim = "sucuklu,kaşarli"
                        },
                        new
                        {
                            Id = 4,
                            Price = 260.0,
                            ProductName = "Pizza5",
                            Tanitim = "sucuklu,kaşarli"
                        },
                        new
                        {
                            Id = 5,
                            Price = 260.0,
                            ProductName = "Pizza6",
                            Tanitim = "sucuklu,kaşarli"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
